### ISSUE TITLE
Still only on one display.

### ISSUE THREAD

**Issue by BenJetson** [franglais125/dash-to-dock#8]
Hey! I heard about your modified version of this shell extension through your comment on OMGUbuntu. I installed it on my testing system today, to no avail. The dock still only appears on the primary display and I couldn't find a setting in the shell extension preferences window to change it. 

#### System Information:
- Ubuntu GNOME 16.04.1
- GNOME Shell 3.18.5
- All software up-to-date.

#### Here are my steps to installing the extension:
1. Remove old instance of `dash-to-dock` via shell extension preferences
2. Clone repository, then `cd` into the directory
3. Run `make` followed by `make install`, no errors reported.
4. Restart GNOME shell by pressing `ALT+F2` and entering `r`
5. Enable the shell extension via GNOME Tweak

 Maybe I just missed something during installation? It'd be great to have the dock on all displays (then I could stop using Plank! :smiley:). Let me know.

**Comment by franglais125** [comment]
Hi! I'm on my phone at the moment, so I don't know if I can be of much help.

You have to turn on a setting. If you open the Settings, it's on the first tab. Something like "Show on all monitors", at the top almost.

If you can't find it, I'll post a screenshot in a few hours!

**Comment by BenJetson** [comment]
I found the problem. I was pulling from the `master` branch instead of the `multi-monitor` branch. The checkbox appeared after reinstallation from the correct source.

![image](https://cloud.githubusercontent.com/assets/10427974/24581896/4ca97732-16f2-11e7-8d2a-f6ea0d2f119f.png)

For anyone else who encounters this issue, clone this branch instead:
https://github.com/franglais125/dash-to-dock/tree/multi_monitor

**Comment by franglais125** [comment]
Glad you got it working... Let me know if you find any bugs!

Every now and then I do a rebase against Michele's master, to include bug fixes and new features, so make sure to `git pull` from time to time :)
