### ISSUE TITLE
Icons overlaped by topbar when using together with another extension. We could have offset option

### ISSUE THREAD

**Issue by yurividal** [franglais125/dash-to-dock#9]
This is not an issue with dash-to-dock itself. But when i use the dash-to-sock extension together with the "Hide Topbar" extension, the top bar stays in front of the dash icon launcher. Could there be an option to set an offset for the icons?  (check screenshot for details: ) 
![screenshot from 2017-04-10 11-43-00](https://cloud.githubusercontent.com/assets/8555749/24867242/fafb99ea-1de2-11e7-8891-ca6783011722.png)

**Comment by franglais125** [comment]
Indeed, this is a known problem. Here is the original issue with more info: https://github.com/micheleg/dash-to-dock/issues/298

Btw, did you try the multi-monitor branch?

**Comment by franglais125** [comment]
Oops, sorry, I linked the wrong issue. Anyway, this was reported before, can't find it now!

Edit: here https://github.com/micheleg/dash-to-dock/issues/334

**Comment by yurividal** [comment]
Thanks for the feedback @franglais125 
I havent tried to install the multi-monitor yet. Actually, i tried to install, but i get an error. Maybe because i am on gnome 3.20.4?

**Comment by franglais125** [comment]
How did you install it?

The proper way is to download the branch (with git for instance) and run:

`make && make install`

**Comment by yurividal** [comment]
Yes my friend! sorry about that. Multi-monitor branch installed and it works perfectly as intended! Thank you very much. In my opinion, it is pretty much ready to be merged on main branch. 

good to know that the icon overlap issue is known. feel free to contact me in case you need any help with testing. =D

**Comment by franglais125** [comment]
Perfect! I'm a trying to get it merged, but it takes time. In any case, check this branch every now and then because I keep it updated with the latest features and bug fixes.

Cheers, and obrigado! (I'll close this issue now)
